In [30]:
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
from tabulate import tabulate

plt.style.use("../auri.mplstyle")
pd.options.display.unicode.east_asian_width = True

In [31]:
parquet_path = Path("../data/processed/주건축물_검증규칙.parquet")
df_orig = pd.read_parquet(parquet_path)
print(f"Loaded shape: {df_orig.shape}")
with pd.option_context("display.max_columns", None):
    print(tabulate(df_orig.head(30), headers="keys", tablefmt="psql"))

Loaded shape: (7364967, 38)
+----+----------------------+---------------------------+--------+-------------------------------------+---------------+---------------+----------------+-------------------+--------------------------------------+-----------------+-----------------+--------------+--------------+---------------------------+--------------+-----------+--------------+--------------+---------------+----------------------+----------------------+-------------------+-------------------+--------------------------------+-------------------+---------------------+----------+----------+-----------------+---------------+----------+-----------------+---------------+----------+----------+---------------+----------+----------+
|    |   관리_건축물대장_PK |   관리_상위_건축물대장_PK | 단독   | 대지_위치                           |   시군구_코드 |   법정동_코드 |   주_용도_코드 | 주_용도_코드_명   | 기타_용도                            |   대지_면적(㎡) |   건축_면적(㎡) |   건폐_율(%) |   연면적(㎡) |   용적_률_산정_연면적(㎡) |   용적_률(%) |   높이(m) |   지상_층_수 |   지하_층_수 |   사용승인_일 |   총괄_대지_면적(㎡) |   총괄_건축_면적(㎡) |   총괄_건폐_율(%) |   총괄_연면적(㎡) |   총괄_용적_률_산정_연면적(㎡) |   총괄_용적_률(%) |   총괄_주_건축물_수 | 기존14   | 기존16   |   건폐율_재계산 |   건폐율_차이 | 기존19   |   용적률_재계산 |   용적률_차이 | 기존20   | 신규01   |   연면적_상한 | 신규02   | 신규03   |
|----+----------------------+---------------------------+--------+-------------------------------------+---------------+---------------+----------------+-------------------+--------------------------------------+-----------------+-----------------+--------------+--------------+---------------------------+--------------+-----------+--------------+--------------+---------------+----------------------+----------------------+-------------------+-------------------+--------------------------------+-------------------+---------------------+----------+----------+-----------------+---------------+----------+-----------------+---------------+----------+----------+---------------+----------+----------|
|  0 |             10021950 |                  10021363 | False  | 서울특별시 종로구 숭인동 201번지    |         11110 |         17500 |          01000 | 단독주택          | 주택                                 |          nan    |          nan    |       nan    |        29.75 |                    nan    |       nan    |    nan    |            1 |            0 |               |               nan    |               nan    |            nan    |             99.17 |                         nan    |            nan    |                   3 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |
|  1 |             10021957 |                  10021366 | False  | 서울특별시 종로구 숭인동 569번지    |         11110 |         17500 |          02000 | 공동주택          | 아파트                               |          513    |          227.82 |        44.4  |      1659.98 |                    659.85 |       281.04 |     20.6  |            7 |            1 |      20001129 |               nan    |               nan    |            nan    |           2507.04 |                         nan    |            nan    |                   4 | False    | False    |         44.4094 |   -0.00935673 | False    |         128.626 |  152.414      | True     | False    |       2107.74 | False    | False    |
|  2 |             10021958 |                  10021366 | False  | 서울특별시 종로구 숭인동 569번지    |         11110 |         17500 |          02000 | 공동주택          | 연립주택                             |          nan    |          nan    |       nan    |       169.38 |                    nan    |       nan    |    nan    |            2 |            0 |      19760702 |               nan    |               nan    |            nan    |           2507.04 |                         nan    |            nan    |                   4 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |
|  3 |             10021973 |                  10021373 | False  | 서울특별시 종로구 숭인동 1132번지   |         11110 |         17500 |          04000 | 제2종근린생활시설 | 영업                                 |          nan    |          nan    |       nan    |        44.33 |                    nan    |       nan    |    nan    |            1 |            0 |      19690930 |               nan    |               nan    |            nan    |             80.59 |                         nan    |            nan    |                   2 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |
|  4 |             10021974 |                  10021373 | False  | 서울특별시 종로구 숭인동 1132번지   |         11110 |         17500 |          04000 | 제2종근린생활시설 | 근린생활시설                         |          nan    |          nan    |       nan    |        36.26 |                    nan    |       nan    |    nan    |            1 |            0 |      19600210 |               nan    |               nan    |            nan    |             80.59 |                         nan    |            nan    |                   2 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |
|  5 |             10021980 |                  10021376 | False  | 서울특별시 종로구 숭인동 1419번지   |         11110 |         17500 |          04000 | 제2종근린생활시설 | 근린생활시설, 근린생활시설(판매시설) |          nan    |          nan    |       nan    |      1411.34 |                    nan    |       nan    |    nan    |            5 |            1 |      19831117 |               nan    |               nan    |            nan    |           1880.27 |                         nan    |            nan    |                   2 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |
|  6 |             10021981 |                  10021377 | False  | 서울특별시 종로구 숭인동 1423번지   |         11110 |         17500 |          07000 | 판매시설          | 점포                                 |          nan    |          nan    |       nan    |      1190.55 |                    nan    |       nan    |    nan    |            3 |            0 |      19680726 |               nan    |               nan    |            nan    |           1428.9  |                         nan    |            nan    |                   2 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |
|  7 |             10021991 |                  10021380 | False  | 서울특별시 종로구 평창동 533-4번지  |         11110 |         18300 |          01000 | 단독주택          | 다가구용 단독주택(2가구)             |          nan    |          136.18 |       nan    |       314.84 |                    236.47 |       nan    |      7    |            2 |            1 |      19950926 |               658    |               183.2  |             27.84 |            361.86 |                         283.49 |             43.08 |                   2 | False    | False    |        nan      |  nan          |          |         nan     |  nan          |          | False    |        930.36 | False    | False    |
|  8 |             10021998 |                  10021383 | False  | 서울특별시 종로구 구기동 150번지    |         11110 |         18200 |          02000 | 공동주택          | 연립주택                             |          nan    |          nan    |       nan    |      2810.43 |                    nan    |       nan    |    nan    |            3 |            1 |      19920817 |               nan    |               nan    |            nan    |           5187.37 |                         nan    |            nan    |                   4 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |
|  9 |            100211003 |                  10021385 | False  | 서울특별시 종로구 부암동 129-10번지 |         11110 |         18400 |          02000 | 공동주택          | 공동주택,다세대주택                  |          nan    |          141.82 |       nan    |       693.41 |                    531.52 |       nan    |     15.6  |            4 |            1 |      20030617 |               793    |               457.42 |             57.68 |           2285.58 |                        1632.33 |            205.84 |                   3 | False    | False    |        nan      |  nan          |          |         nan     |  nan          |          | False    |       1360.28 | False    | False    |
| 10 |            100211006 |                  10021386 | False  | 서울특별시 종로구 평창동 180-2번지  |         11110 |         18300 |          06000 | 종교시설          | 문화및집회시설                       |          nan    |          120.47 |       nan    |       267.8  |                    184.58 |       nan    |      6.7  |            2 |            1 |      19890919 |               624    |               254.84 |             40.84 |            500.65 |                         390.95 |             62.65 |                   2 | False    | False    |        nan      |  nan          |          |         nan     |  nan          |          | False    |        864.94 | False    | False    |
| 11 |            100211007 |                  10021386 | False  | 서울특별시 종로구 평창동 180-2번지  |         11110 |         18300 |          04000 | 제2종근린생활시설 | 사찰                                 |          nan    |          126.81 |       nan    |       232.85 |                    198.81 |       nan    |      7.8  |            2 |            0 |      19680821 |               624    |               254.84 |             40.84 |            500.65 |                         390.95 |             62.65 |                   2 | False    | False    |        nan      |  nan          |          |         nan     |  nan          |          | False    |        253.62 | False    | False    |
| 12 |            100211014 |                  10021390 | False  | 서울특별시 종로구 구기동 10-5번지   |         11110 |         18200 |          01000 | 단독주택          | 주택                                 |          nan    |           66.12 |       nan    |       126.96 |                    126.96 |       nan    |      6.2  |            2 |            0 |      20030728 |               945.92 |               282.93 |             29.91 |            712.46 |                         533.95 |             56.45 |                   4 | False    | False    |        nan      |  nan          |          |         nan     |  nan          |          | False    |        132.24 | False    | False    |
| 13 |            100211015 |                  10021390 | False  | 서울특별시 종로구 구기동 10-5번지   |         11110 |         18200 |          03000 | 제1종근린생활시설 | 제1종근린생활시설                    |          nan    |          100.7  |       nan    |       380.18 |                    201.4  |       nan    |      5.28 |            2 |            1 |      20030418 |               945.92 |               282.93 |             29.91 |            712.46 |                         533.95 |             56.45 |                   4 | False    | False    |        nan      |  nan          |          |         nan     |  nan          |          | False    |       1147.32 | False    | False    |
| 14 |            100211017 |                  10021391 | False  | 서울특별시 종로구 효제동 160-1번지  |         11110 |         16200 |          18000 | 창고시설          | 창고시설                             |          nan    |          151.96 |       nan    |      1147.64 |                   1147.64 |       nan    |     25.7  |            8 |            0 |      20030822 |               608    |               364.26 |             59.91 |           2813.1  |                        2387.83 |            392.74 |                   2 | False    | False    |        nan      |  nan          |          |         nan     |  nan          |          | False    |       1215.68 | False    | False    |
| 15 |            100211019 |                  10021392 | False  | 서울특별시 종로구 구기동 10-18번지  |         11110 |         18200 |          02000 | 공동주택          | 공동주택,다세대주택                  |          nan    |          nan    |       nan    |       297.27 |                    nan    |       nan    |      7.9  |            2 |            2 |      20030905 |               983    |               290.99 |             29.6  |           1221.89 |                         549.48 |             55.9  |                   2 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |
| 16 |            100211020 |                  10021392 | False  | 서울특별시 종로구 구기동 10-18번지  |         11110 |         18200 |          02000 | 공동주택          | 공동주택,다세대주택                  |          nan    |          nan    |       nan    |       924.62 |                    nan    |       nan    |      7.9  |            2 |            2 |      20030905 |               983    |               290.99 |             29.6  |           1221.89 |                         549.48 |             55.9  |                   2 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |
| 17 |            100211025 |                  10021393 | False  | 서울특별시 종로구 창신동 702번지    |         11110 |         17400 |          02000 | 공동주택          | 공동주택(아파트)                     |        24923.1  |          nan    |       nan    |     11443.7  |                    nan    |       nan    |    nan    |           14 |            1 |      19921125 |             24923.1  |               nan    |            nan    |          59593.7  |                         nan    |            nan    |                   6 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |
| 18 |            100211026 |                  10021393 | False  | 서울특별시 종로구 창신동 702번지    |         11110 |         17400 |          07000 | 판매시설          | 판매시설,종교시설                    |        24923.1  |          nan    |       nan    |      3221.71 |                    nan    |       nan    |    nan    |            4 |            1 |      19921125 |             24923.1  |               nan    |            nan    |          59593.7  |                         nan    |            nan    |                   6 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |
| 19 |            100211032 |                  10021396 | False  | 서울특별시 종로구 인의동 50-2번지   |         11110 |         15700 |          03000 | 제1종근린생활시설 | 근린생활시설                         |          614.52 |          338.25 |        55.04 |      2025.42 |                   1687.41 |       274.59 |     17.3  |            5 |            1 |      19821012 |               614.52 |               338.25 |             55.04 |           2045.25 |                        1687.41 |            274.59 |                   2 | False    | False    |         55.043  |   -0.00296036 | False    |         274.59  |    7.6157e-05 | False    | False    |       2305.77 | False    | False    |
| 20 |            100211038 |                  10021399 | False  | 서울특별시 종로구 구기동 88-40번지  |         11110 |         18200 |          04000 | 제2종근린생활시설 | 근린생활시설                         |          nan    |           47.54 |       nan    |       120.18 |                    120.18 |       nan    |    nan    |            2 |            0 |      19710915 |               331    |               193.01 |             58.31 |            346.41 |                         313.11 |             94.6  |                   2 | False    | False    |        nan      |  nan          |          |         nan     |  nan          |          | False    |         95.08 | True     | False    |
| 21 |            100211040 |                  10021400 | False  | 서울특별시 종로구 평창동 175-7번지  |         11110 |         18300 |          02000 | 공동주택          | 연립주택                             |          nan    |          nan    |       nan    |       903.76 |                    nan    |       nan    |    nan    |            3 |            1 |      19860628 |               nan    |               nan    |            nan    |           5050.81 |                         nan    |            nan    |                   3 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |
| 22 |            100211041 |                  10021400 | False  | 서울특별시 종로구 평창동 175-7번지  |         11110 |         18300 |          02000 | 공동주택          | 관리실                               |          nan    |          nan    |       nan    |        10    |                    nan    |       nan    |    nan    |            1 |            0 |      19860612 |               nan    |               nan    |            nan    |           5050.81 |                         nan    |            nan    |                   3 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |
| 23 |            100211043 |                  10021401 | False  | 서울특별시 종로구 평창동 176번지    |         11110 |         18300 |          02000 | 공동주택          | 연립주택                             |          nan    |          nan    |       nan    |      2188.5  |                    nan    |       nan    |    nan    |            3 |            0 |      19860910 |               nan    |               nan    |            nan    |           4961.68 |                         nan    |            nan    |                   3 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |
| 24 |            100211045 |                  10021401 | False  | 서울특별시 종로구 평창동 176번지    |         11110 |         18300 |          02000 | 공동주택          | 지하차고, 수위실                     |          nan    |          nan    |       nan    |       195.44 |                    nan    |       nan    |    nan    |            1 |            1 |      19860910 |               nan    |               nan    |            nan    |           4961.68 |                         nan    |            nan    |                   3 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |
| 25 |            100211046 |                  10021402 | False  | 서울특별시 종로구 평창동 179-1번지  |         11110 |         18300 |          02000 | 공동주택          | 연립주택                             |          nan    |          nan    |       nan    |      2664.92 |                    nan    |       nan    |    nan    |            3 |            1 |      19860812 |               nan    |               nan    |            nan    |          14495.2  |                         nan    |            nan    |                   6 |          |          |        nan      |  nan          |          |         nan     |  nan          |          |          |        nan    |          | False    |

In [32]:
df_results = pd.read_parquet("../results/area_data_anomaly.parquet")
df_results = df_results.convert_dtypes()
print(f"Loaded shape: {df_results.shape}")
with pd.option_context("display.max_columns", None):
    print(tabulate(df_results.head(30), headers="keys", tablefmt="psql"))

Loaded shape: (7364967, 11)
+----+----------------------+-------------+---------------+----------------+----------+----------+----------+----------+----------+----------+----------+
|    |   관리_건축물대장_PK |   시도_코드 | 사용승인_년   |   주_용도_코드 | 기존14   | 기존16   | 기존19   | 기존20   | 신규01   | 신규02   | 이상값   |
|----+----------------------+-------------+---------------+----------------+----------+----------+----------+----------+----------+----------+----------|
|  0 |             10021950 |          11 | <NA>          |          01000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
|  1 |             10021957 |          11 | 2000          |          02000 | False    | False    | False    | True     | False    | False    | False    |
|  2 |             10021958 |          11 | 1976          |          02000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
|  3 |             10021973 |          11 | 1969          |          04000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
|  4 |             10021974 |          11 | 1960          |          04000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
|  5 |             10021980 |          11 | 1983          |          04000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
|  6 |             10021981 |          11 | 1968          |          07000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
|  7 |             10021991 |          11 | 1995          |          01000 | False    | False    | <NA>     | <NA>     | False    | False    | False    |
|  8 |             10021998 |          11 | 1992          |          02000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
|  9 |            100211003 |          11 | 2003          |          02000 | False    | False    | <NA>     | <NA>     | False    | False    | False    |
| 10 |            100211006 |          11 | 1989          |          06000 | False    | False    | <NA>     | <NA>     | False    | False    | False    |
| 11 |            100211007 |          11 | 1968          |          04000 | False    | False    | <NA>     | <NA>     | False    | False    | False    |
| 12 |            100211014 |          11 | 2003          |          01000 | False    | False    | <NA>     | <NA>     | False    | False    | False    |
| 13 |            100211015 |          11 | 2003          |          03000 | False    | False    | <NA>     | <NA>     | False    | False    | False    |
| 14 |            100211017 |          11 | 2003          |          18000 | False    | False    | <NA>     | <NA>     | False    | False    | False    |
| 15 |            100211019 |          11 | 2003          |          02000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
| 16 |            100211020 |          11 | 2003          |          02000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
| 17 |            100211025 |          11 | 1992          |          02000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
| 18 |            100211026 |          11 | 1992          |          07000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
| 19 |            100211032 |          11 | 1982          |          03000 | False    | False    | False    | False    | False    | False    | False    |
| 20 |            100211038 |          11 | 1971          |          04000 | False    | False    | <NA>     | <NA>     | False    | True     | False    |
| 21 |            100211040 |          11 | 1986          |          02000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
| 22 |            100211041 |          11 | 1986          |          02000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
| 23 |            100211043 |          11 | 1986          |          02000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
| 24 |            100211045 |          11 | 1986          |          02000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
| 25 |            100211046 |          11 | 1986          |          02000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
| 26 |            100211047 |          11 | 1986          |          02000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
| 27 |            100211049 |          11 | 1986          |          02000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
| 28 |            100211051 |          11 | 1986          |          02000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
| 29 |            100211053 |          11 | 1986          |          02000 | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     | <NA>     |
+----+----------------------+-------------+---------------+----------------+----------+----------+----------+----------+----------+----------+----------+

In [33]:
df_results.dtypes

관리_건축물대장_PK    string[python]
시도_코드             string[python]
사용승인_년           string[python]
주_용도_코드          string[python]
기존14                       boolean
기존16                       boolean
기존19                       boolean
기존20                       boolean
신규01                       boolean
신규02                       boolean
이상값                       boolean
dtype: object

In [34]:
df_results.head()

,관리_건축물대장_PK,시도_코드,사용승인_년,주_용도_코드,기존14,기존16,기존19,기존20,신규01,신규02,이상값
0,10021950,11,<NA>,01000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,10021957,11,2000,02000,False,False,False,True,False,False,False
2,10021958,11,1976,02000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,10021973,11,1969,04000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,10021974,11,1960,04000,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

---

시도별, 연도별 표를 만들어보자.

In [35]:
df_year = pd.DataFrame(
    {
        "사용승인_년": [f"{year:04d}" for year in range(1950, 2025)],
    }
)
df_year

   사용승인_년
0         1950
1         1951
2         1952
3         1953
4         1954
..         ...
70        2020
71        2021
72        2022
73        2023
74        2024

[75 rows x 1 columns]

In [36]:
df_usage = df_orig[["주_용도_코드", "주_용도_코드_명"]].drop_duplicates()
df_usage = df_usage.set_index("주_용도_코드").sort_index()
df_usage = df_usage.reindex(
    index=[f"{i:02d}000" for i in range(1, 34)]
)  # 01000, 02000, …
df_usage

                   주_용도_코드_명
주_용도_코드
01000                     단독주택
02000                     공동주택
03000            제1종근린생활시설
04000            제2종근린생활시설
05000               문화및집회시설
06000                     종교시설
07000                     판매시설
08000                     운수시설
09000                     의료시설
10000                 교육연구시설
11000                   노유자시설
12000                     수련시설
13000                     운동시설
14000                     업무시설
15000                     숙박시설
16000                     위락시설
17000                         공장
18000                     창고시설
19000         위험물저장및처리시설
20000               자동차관련시설
21000           동물및식물관련시설
22000          분뇨.쓰레기처리시설
23000               교정및군사시설
24000                 방송통신시설
25000                     발전시설
26000                 묘지관련시설
27000                 관광휴게시설
28000                   가설건축물
29000                     장례시설
30000             자원순환관련시설
31000                   야영장시설
32000                     교정시설
33000                국방,군사시설

In [37]:
df_kcad = pd.read_csv(
    "../data/processed/code_kcad_sgg_2024.csv", dtype="string"
).sort_values("행정구역분류")
df_kcad["시도_코드"] = df_kcad["시군구코드"].str[:2]
df_sido = df_kcad[["시도_코드", "시도"]].drop_duplicates()
df_sido

    시도_코드            시도
0          11      서울특별시
25         26      부산광역시
41         27      대구광역시
50         28      인천광역시
60         29      광주광역시
65         30      대전광역시
70         31      울산광역시
75         36  세종특별자치시
76         41          경기도
127        51  강원특별자치도
150        43        충청북도
160        44        충청남도
177        52  전북특별자치도
193        46        전라남도
215        47        경상북도
245        48        경상남도
262        50  제주특별자치도

In [38]:
df_results.shape

(7364967, 11)

In [39]:
df_results["기존16"].value_counts(dropna=False)

기존16
False    6647554
True      373505
<NA>      343908
Name: count, dtype: Int64

In [40]:
# mean()은 NA 제외하고 계산

print(df_results["기존16"].mean())
print(373505 / (7364967 - 343908))

0.05319781531532494
0.05319781531532494

In [41]:
# NA → False로 처리

print(df_results["기존16"].astype("boolean").fillna(False).mean())
print(373505 / (7364967))

0.05071373707444989
0.05071373707444989

In [42]:
# NA → False로 처리한 df 준비
# Convert columns to the best possible dtypes using dtypes supporting pd.NA
df_gb = df_results.iloc[:, 1:].copy().convert_dtypes()
df_gb.iloc[:, 3:] = df_gb.iloc[:, 3:].fillna(False)  # NA → False
df_gb

,시도_코드,사용승인_년,주_용도_코드,기존14,기존16,기존19,기존20,신규01,신규02,이상값
0,11,<NA>,01000,False,False,False,False,False,False,False
1,11,2000,02000,False,False,False,True,False,False,False
2,11,1976,02000,False,False,False,False,False,False,False
3,11,1969,04000,False,False,False,False,False,False,False
4,11,1960,04000,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
7364962,46,2014,01000,False,False,False,False,False,False,False
7364963,46,2014,01000,False,False,False,False,False,False,False
7364964,46,2014,04000,False,False,False,False,False,False,False
7364965,46,2014,21000,False,False,False,False,False,False,False
7364966,46,2014,21000,False,False,False,False,False,False,False

In [43]:
df_gb.dtypes

시도_코드       string[python]
사용승인_년     string[python]
주_용도_코드    string[python]
기존14                 boolean
기존16                 boolean
기존19                 boolean
기존20                 boolean
신규01                 boolean
신규02                 boolean
이상값                 boolean
dtype: object

In [44]:
gb = (
    df_gb.iloc[:, [0, *range(3, df_gb.shape[1])]]
    .groupby("시도_코드")
    .mean()
    .astype(float)
    .mul(100)
    .round(2)
)
df_ratio = df_sido.set_index("시도_코드").join(gb)
df_ratio

,시도,기존14,기존16,기존19,기존20,신규01,신규02,이상값
시도_코드,,,,,,,,
11,서울특별시,0.08,0.25,1.09,0.88,0.09,0.19,0.70
26,부산광역시,0.09,1.77,1.17,1.06,0.17,0.47,0.43
27,대구광역시,0.15,2.95,1.31,1.59,0.31,0.64,0.33
28,인천광역시,0.10,2.25,0.80,1.00,0.24,0.45,0.26
29,광주광역시,0.08,1.59,4.14,2.65,0.51,1.00,0.19
30,대전광역시,0.09,2.21,1.25,1.58,0.21,0.36,0.20
31,울산광역시,0.07,5.42,2.92,3.11,0.38,0.86,0.21
36,세종특별자치시,0.30,6.58,0.42,0.56,0.68,1.21,0.07
41,경기도,0.10,3.33,1.13,1.07,0.31,0.82,0.29
51,강원특별자치도,0.07,5.69,0.85,1.04,0.18,0.72,0.24
43,충청북도,0.11,6.98,0.88,0.90,0.28,0.91,0.19
44,충청남도,0.10,7.52,0.52,0.54,0.34,0.90,0.24
52,전북특별자치도,0.22,8.12,0.78,0.74,0.26,1.33,0.34
46,전라남도,0.29,4.36,1.36,1.18,0.27,0.94,0.35
47,경상북도,0.15,8.92,1.31,1.35,0.27,1.17,0.31
48,경상남도,0.13,5.70,0.74,0.69,0.23,1.15,0.25
50,제주특별자치도,0.12,10.34,2.88,2.62,0.28,1.00,0.24

In [45]:
df_ratio.to_csv(
    "../results/area_data_anomaly_ratio_by_sido.csv", index=True, encoding="utf-8-sig"
)

In [26]:
df_orig["기존14"].value_counts(dropna=False)

기존14
False    5190727
None     2164467
True        9773
Name: count, dtype: int64

In [27]:
df_orig[df_orig["시군구_코드"].str.startswith("38")]

,관리_건축물대장_PK,관리_상위_건축물대장_PK,단독,대지_위치,시군구_코드,법정동_코드,주_용도_코드,주_용도_코드_명,기타_용도,대지_면적(㎡),...,건폐율_재계산,건폐율_차이,기존19,용적률_재계산,용적률_차이,기존20,신규01,연면적_상한,신규02,신규03
3405802,12311844,None,True,974-2번지,38022,38022,01000,단독주택,단독주택,NaN,...,NaN,NaN,None,NaN,NaN,None,False,NaN,None,False

---

연도

In [50]:
# Convert columns to the best possible dtypes using dtypes supporting pd.NA
df_gb = df_results.iloc[:, 1:].copy().convert_dtypes()
df_gb.iloc[:, 3:] = df_gb.iloc[:, 3:].fillna(False)  # NA → False

key_col = "사용승인_년"

gb = (
    df_gb.iloc[:, [1, *range(3, df_gb.shape[1])]]
    .groupby(key_col)
    .mean()
    .astype(float)
    .mul(100)
    .round(2)
)

df_ratio_year = df_year.set_index(key_col).join(gb).fillna("-")
with pd.option_context("display.max_rows", None):
    display(df_ratio_year)

             기존14  기존16  기존19  기존20  신규01  신규02  이상값
사용승인_년
1950           0.29    0.44    0.58    0.50    0.19    0.19    0.29
1951           0.43    0.36    0.49    0.40    0.14    0.20    0.25
1952           0.28    0.33    0.58    0.52    0.16    0.12    0.37
1953           0.31    0.33    0.53    0.46    0.14    0.13    0.33
1954           0.24    0.30    0.45    0.40    0.14    0.15    0.33
1955           0.21    0.43    0.61    0.51    0.17    0.17    0.31
1956           0.22    0.44    0.62    0.57    0.17    0.16    0.29
1957           0.22    0.42    0.54    0.51    0.18    0.16    0.35
1958           0.23    0.38    0.76    0.66    0.18    0.16    0.37
1959           0.20    0.40    0.74    0.69    0.17    0.21    0.27
1960           0.25    0.47    1.00    0.87    0.13    0.21    0.27
1961           0.19    0.40    0.78    0.73    0.17    0.18    0.28
1962           0.16    0.39    0.47    0.45    0.24    0.09    0.35
1963           0.35    0.36    0.51    0.42    0.18    0.23    0.35
1964           0.34    0.36    0.58    0.54    0.17    0.25    0.19
1965           0.28    0.54    0.55    0.46    0.24    0.18    0.27
1966           0.26    0.45    0.44    0.41    0.16    0.26    0.35
1967           0.29    0.54    0.37    0.33    0.25    0.27    0.37
1968           0.30    0.50    0.47    0.40    0.25    0.24    0.33
1969           0.28    0.36    0.56    0.43    0.19    0.37    0.33
1970           0.28    0.54    0.61    0.53    0.21    0.31    0.34
1971           0.21    0.42    0.51    0.46    0.17    0.35    0.36
1972           0.32    0.50    0.61    0.54    0.19    0.34    0.38
1973           0.19    0.40    0.49    0.46    0.22    0.34    0.34
1974           0.16    0.40    0.61    0.46    0.21    0.34    0.36
1975           0.16    0.40    0.57    0.47    0.21    0.35    0.31
1976           0.17    0.49    0.49    0.47    0.24    0.35    0.35
1977           0.18    0.43    0.63    0.53    0.22    0.33    0.33
1978           0.16    0.45    0.55    0.47    0.25    0.35    0.32
1979           0.19    0.49    0.61    0.56    0.26    0.38    0.32
1980           0.20    0.45    0.61    0.58    0.25    0.50    0.27
1981           0.25    0.52    0.66    0.59    0.27    0.55    0.31
1982           0.17    0.51    0.68    0.68    0.21    0.48    0.28
1983           0.16    0.48    0.72    0.74    0.20    0.41    0.34
1984           0.18    0.68    0.92    0.96    0.30    0.45    0.34
1985           0.11    0.53    0.60    0.60    0.21    0.28    0.33
1986           0.14    0.84    0.98    0.91    0.24    0.45    0.38
1987           0.11    0.86    1.05    0.98    0.23    0.42    0.32
1988           0.11    0.81    1.21    1.11    0.20    0.40    0.35
1989           0.15    0.71    1.22    1.19    0.16    0.44    0.35
1990           0.12    0.79    1.17    1.16    0.20    0.42    0.33
1991           0.13    0.91    1.44    1.38    0.20    0.47    0.35
1992           0.23    2.82    3.08    2.96    0.36    0.75    0.34
1993           0.26    4.73    4.72    4.72    0.57    1.12    0.34
1994           0.34    5.61    5.04    5.09    0.65    1.38    0.35
1995           0.28    6.48    5.05    4.84    0.58    1.48    0.32
1996           0.22    7.15    4.89    4.93    0.51    1.44    0.34
1997           0.21    8.67    4.76    5.12    0.43    1.24    0.32
1998           0.19    9.81    2.89    2.81    0.50    1.07    0.32
1999           0.14   10.56    2.22    2.11    0.41    1.02    0.29
2000           0.12    9.73    2.07    1.71    0.42    1.02    0.32
2001           0.13    8.28    1.59    1.28    0.34    0.97    0.32
2002           0.08    6.88    1.26    0.94    0.37    0.90    0.33
2003           0.06    7.83    1.00    0.68    0.37    1.02    0.35
2004           0.02    9.10    0.80    0.58    0.40    1.21    0.35
2005           0.01    9.97    0.67    0.39    0.31    1.55    0.28
2006           0.03   10.35    0.59    0.38    0.31    1.60    0.32
2007           0.03   10.19    0.66    0.44    0.39    1.48    0.31
2008           0.01    9.90    0.39    0.29    0.38    1.30    0.29
2009           0.01   10.72    0.23    0.20    0.21    1.21    0.32
2010           0.03    9.64    0.14    0.19    0.16    1.51    0.31
2011           0.03    9.41    0.09    0.19    0.19    1.33    0.32
2012           0.03    9.17    0.12    0.18    0.18    1.09    0.32
2013           0.02    9.58    0.14    0.19    0.23    1.05    0.28
2014           0.02    8.92    0.12    0.20    0.18    0.96    0.34
2015           0.03    8.67    0.13    0.18    0.17    1.03    0.33
2016           0.03    7.98    0.13    0.17    0.17    1.05    0.30
2017           0.02    7.91    0.13    0.20    0.16    1.12    0.30
2018           0.02    7.69    0.11    0.17    0.13    1.40    0.29
2019           0.02    7.93    0.10    0.12    0.09    1.60    0.32
2020           0.02    8.42    0.11    0.12    0.06    1.77    0.33
2021           0.02    8.72    0.12    0.14    0.05    1.62    0.31
2022           0.02    8.58    0.19    0.21    0.05    1.42    0.31
2023           0.01    9.15    0.25    0.25    0.05    1.31    0.30
2024           0.01    9.78    0.19    0.16    0.04    1.21    0.27

In [51]:
df_ratio_year.to_csv(
    "../results/area_data_anomaly_ratio_by_year.csv", index=True, encoding="utf-8-sig"
)

---

용도

In [53]:
# Convert columns to the best possible dtypes using dtypes supporting pd.NA
df_gb = df_results.iloc[:, 1:].copy().convert_dtypes()
df_gb.iloc[:, 3:] = df_gb.iloc[:, 3:].fillna(False)  # NA → False

key_col = "주_용도_코드"

gb = (
    df_gb.iloc[:, [2, *range(3, df_gb.shape[1])]]
    .groupby(key_col)
    .mean()
    .astype(float)
    .mul(100)
    .round(2)
)

df_ratio_usage = df_usage.join(gb).fillna("-")
with pd.option_context("display.max_rows", None):
    display(df_ratio_usage)

,주_용도_코드_명,기존14,기존16,기존19,기존20,신규01,신규02,이상값
주_용도_코드,,,,,,,,
01000,단독주택,0.11,5.91,0.99,0.87,0.23,0.48,0.31
02000,공동주택,0.25,0.85,3.12,3.46,0.29,0.39,0.38
03000,제1종근린생활시설,0.24,4.27,1.08,1.08,0.29,0.70,0.33
04000,제2종근린생활시설,0.12,3.77,0.96,1.00,0.31,0.82,0.35
05000,문화및집회시설,0.12,7.99,0.85,0.75,0.30,0.94,0.30
06000,종교시설,0.13,5.02,1.38,1.48,0.52,1.32,0.31
07000,판매시설,0.34,3.90,1.11,1.21,0.26,0.94,0.42
08000,운수시설,0.15,13.34,1.22,0.87,0.44,1.10,0.29
09000,의료시설,0.17,1.25,0.73,1.00,0.30,0.90,0.36
10000,교육연구시설,0.17,4.31,0.95,1.01,0.39,1.39,0.32
11000,노유자시설,0.10,11.70,1.24,1.19,0.39,0.98,0.28
12000,수련시설,0.10,8.75,0.36,0.33,0.28,0.97,0.13
13000,운동시설,0.13,10.56,0.69,0.76,0.34,1.18,0.38
14000,업무시설,0.15,0.86,1.06,1.31,0.19,0.59,0.56
15000,숙박시설,0.14,4.00,0.90,1.31,0.40,0.59,0.30
16000,위락시설,0.42,2.40,1.02,1.12,0.49,1.36,0.34
17000,공장,0.10,5.34,1.18,1.11,0.41,2.97,0.28
18000,창고시설,0.10,3.66,1.19,1.15,0.20,0.62,0.30
19000,위험물저장및처리시설,0.06,8.09,1.32,1.35,0.42,1.71,0.32
20000,자동차관련시설,0.09,6.11,1.18,1.10,0.36,1.21,0.33
21000,동물및식물관련시설,0.12,4.58,1.10,1.03,0.26,3.87,0.28
22000,분뇨.쓰레기처리시설,0.05,6.47,1.12,1.07,0.24,1.52,0.22
23000,교정및군사시설,0.02,11.41,0.24,0.19,0.08,1.03,0.32
24000,방송통신시설,0.10,4.44,1.81,1.75,0.29,0.29,0.32
25000,발전시설,0.00,8.47,0.16,0.33,0.16,0.79,0.37
26000,묘지관련시설,0.13,9.52,1.12,1.26,0.07,0.66,0.26
27000,관광휴게시설,0.13,13.30,0.58,0.49,0.20,1.03,0.37
28000,가설건축물,0.00,6.67,0.00,0.00,0.00,0.00,0.00
29000,장례시설,0.00,6.18,0.48,0.71,0.48,0.48,0.00
30000,자원순환관련시설,0.03,6.64,0.45,0.46,0.15,2.72,0.36
31000,야영장시설,0.02,6.68,0.22,0.32,0.07,0.41,0.30
32000,교정시설,0.00,16.00,0.00,0.00,0.00,0.00,0.00
33000,"국방,군사시설",0.00,17.13,0.02,0.02,0.06,0.58,0.22

In [54]:
df_ratio_usage.to_csv(
    "../results/area_data_anomaly_ratio_by_usage.csv", index=True, encoding="utf-8-sig"
)